stages:
    - build

minify-js:
  image: node:latest
  stage: build
  script:
    - npm install uglify-js -g
    - mkdir -p ./public
    - uglifyjs ./classloc-form-snippet.js -o public/clsnjs.js -c -m